//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatafirstMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        [Display (Name ="Album")]
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Label { get; set; }
        public bool WonGrammy { get; set; }
        public int ArtistID { get; set; }
        public string Photo { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
